-- Flyway migration: create profile table and sequence for Oracle

-- Create sequence
CREATE SEQUENCE PROFILE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Create table
CREATE TABLE PROFILE (
  ID NUMBER(19) PRIMARY KEY,
  USERNAME VARCHAR2(100) NOT NULL,
  DISPLAY_NAME VARCHAR2(200),
  EMAIL VARCHAR2(200) NOT NULL,
  BIO VARCHAR2(2000),
  AVATAR_URL VARCHAR2(500),
  PASSWORD_HASH VARCHAR2(500) NOT NULL,
  CREATED_AT TIMESTAMP
);

-- Unique constraints via unique indexes
CREATE UNIQUE INDEX UQ_PROFILE_USERNAME ON PROFILE (USERNAME);
CREATE UNIQUE INDEX UQ_PROFILE_EMAIL ON PROFILE (EMAIL);

