-- Flyway migration to create MESSAGE table and sequence
CREATE SEQUENCE MESSAGE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE MESSAGE (
  ID NUMBER(19) PRIMARY KEY,
  SENDER_ID NUMBER(19) NOT NULL,
  RECIPIENT_ID NUMBER(19) NOT NULL,
  CONTENT VARCHAR2(5000),
  IS_READ NUMBER(1) DEFAULT 0,
  CREATED_AT TIMESTAMP
);

CREATE INDEX IDX_MESSAGE_RECIPIENT ON MESSAGE (RECIPIENT_ID);

