-- Flyway migration V5: create NOTIFICATION table for storing user notifications (Oracle)

-- Create sequence for notification IDs
CREATE SEQUENCE NOTIFICATION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Create table
CREATE TABLE NOTIFICATION (
  ID NUMBER(19) PRIMARY KEY,
  USER_ID NUMBER(19) NOT NULL,
  TYPE VARCHAR2(255),
  PAYLOAD VARCHAR2(2000),
  READ_FLAG NUMBER(1) DEFAULT 0,
  CREATED_AT TIMESTAMP
);

-- Index for fast lookup by user
CREATE INDEX IDX_NOTIFICATION_USER ON NOTIFICATION (USER_ID);

-- Trigger to populate ID from sequence if not provided
CREATE OR REPLACE TRIGGER TRG_NOTIFICATION_ID
BEFORE INSERT ON NOTIFICATION
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT NOTIFICATION_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

COMMIT;

