-- Flyway migration V6: create REPORT table for user content reports (Oracle)

CREATE SEQUENCE REPORT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE REPORT (
  ID NUMBER(19) PRIMARY KEY,
  REPORTER_ID NUMBER(19) NOT NULL,
  CONTENT_TYPE VARCHAR2(100) NOT NULL,
  CONTENT_ID NUMBER(19) NOT NULL,
  REASON VARCHAR2(2000),
  CREATED_AT TIMESTAMP
);

CREATE INDEX IDX_REPORT_CONTENT_TYPE ON REPORT (CONTENT_TYPE);

CREATE OR REPLACE TRIGGER TRG_REPORT_ID
BEFORE INSERT ON REPORT
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT REPORT_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

COMMIT;

